version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: memex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: memex
      POSTGRES_PASSWORD: memex
      POSTGRES_DB: memex
    ports:
      - "5432:5432"
    volumes:
      - memex-db-data:/var/lib/postgresql/data

volumes:
  memex-db-data:
    driver: local
