version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: synap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: synap
      POSTGRES_PASSWORD: synap
      POSTGRES_DB: synap
    ports:
      - "5432:5432"
    volumes:
      - synap-db-data:/var/lib/postgresql/data

volumes:
  synap-db-data:
    driver: local
